version: '3.8'

services:
  sqlserver:
    build: .
    environment:
      SA_PASSWORD: "Olaola123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
